### ISSUE TITLE
Any new features?

### ISSUE THREAD

**Issue by goops17** [goops17/flutter_rating#5]
Hello everyone, 
If you want any new features in the rating system please write it down below.

**Comment by franzejr** [comment]
readonly mode?

**Comment by goops17** [comment]
Can you briefly explain about the mode please?

**Comment by heath3n** [comment]
@goops17 I think what @franzejr means is that sometimes you might want to show the rating but not let the user edit it. For example, a rating bar might be shown to display the average rating from a number of reviews; obviously the user cannot edit this rating directly.

I would also love to see this feature.

**Comment by goops17** [comment]
Sounds like good idea. Anyone wants to implement it?

**Comment by heath3n** [comment]
Seems easy enough; I will try to submit a PR tonight

**Comment by shinriyo** [comment]
I agree with @franzejr 
vertical, horizontal mode.

They are your rival ;>
https://github.com/buraktabn/starreviews
https://github.com/buraktabn/give-star-reviews

**Comment by shinriyo** [comment]
@goops17 
Custom Icon or Image options.

**Comment by goops17** [comment]
@shinriyo do you want to work on any of these?

**Comment by shinriyo** [comment]
@goops17 Wow. Quick response.
I desire `readonly mode`.

**Comment by goops17** [comment]
@shinriyo go ahead with readonly mode.
I can improve this plugin on weekends.

**Comment by shinriyo** [comment]
@goops17 Do you mean that I fix and pull-request for it?

**Comment by goops17** [comment]
sure

**Comment by shinriyo** [comment]
just commented out them. it will be read-only 
```
//              onRatingChanged: (rating) => setState(
//                    () {
//                      this.rating = rating;
//                    },
//                  ),
```

**Comment by shinriyo** [comment]
@goops17 
fill or border option for empty star

**Comment by goops17** [comment]
updated with latest commit
