### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Robert126** [goops17/flutter_rating#7]
First of all thank you for your great work! The plugin works great

Are you working on Null safety and can you let me now when you will release the upgrade?

Kind regards,
Robert

**Comment by alamin-karno** [comment]
I also faced problems with this, so I updated the code with null safety. I already make PR with an invalid safety version. 

@goops17 check & accept the merge if there is no conflict.

LINK: #8

**Comment by alamin-karno** [comment]
I had to make PR to update null-safety, but the author didn't accept it. So I have created a new package with the help of this package with null-safety enabled and added half star selection option. 

**Check out the package: [flutter_rating_native](https://pub.dev/packages/flutter_rating_native)**
